baseURL = 'https://potatocanonical.com/'
languageCode = 'en-us'
title = 'potatocanonical'
theme = 'smol'

# Parameters
[params]
    subtitle = ""
    dateFmt = "01.02.2006 3:04 PM"

# Header
[menu]
  [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 1 

  [[menu.main]]
        identifier = "categories"
        name = "Categories"
        url = "/categories/"
        weight = 2 

  [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 3

# Footer

    [[menu.footer]]
        name = "mastodon"
        url = "https://infosec.exchange/@mose"
        weight = 1

    [[menu.footer]]
        name = "rss"
        url = "/index.xml"
        weight = 2 

enableGitInfo = true

enableRobotsTXT = true
